export const ActionType = {
    SEARCH: "SEARCH_TAG",
    TOGGLE_DETAIL: "TOGGLE_DETAIL",
    UPDATE_DETAIL: "UPDATE_DETAIL",
    SAVE_DETAIL: "SAVE_DETAIL",
    DELETE_TODO: "DELETE_TODO",
    SORT: "SORT"
};